export const BOOTLOADER_MAX_BYTE_LENGTH = 2 ** 12; // 4 KiB
export const TEXTMODE_FONT_BYTE_LENGTH = 2 ** 12; // 4 KiB

export const BOOTLOADER_OFFSET = 0;
export const TEXTMODE_FONT_OFFSET = BOOTLOADER_MAX_BYTE_LENGTH;
